USE xmojzi07;

DROP TABLE IF EXISTS USER_MAGAZINE;
DROP TABLE IF EXISTS USER_VOLUME;
DROP TABLE IF EXISTS USER_GENRE;
DROP TABLE IF EXISTS VOLUME_CHAPTER;
DROP TABLE IF EXISTS MAGAZINE_CHAPTER;
DROP TABLE IF EXISTS ADDITIONAL_DATA;
DROP TABLE IF EXISTS VOLUME;
DROP TABLE IF EXISTS MAGAZINE;
DROP TABLE IF EXISTS CHAPTER;
DROP TABLE IF EXISTS MANGA_CHARACT;
DROP TABLE IF EXISTS PAGE_CHARACT;
DROP TABLE IF EXISTS PAGE;
DROP TABLE IF EXISTS USER_CHARACT;
DROP TABLE IF EXISTS CHARACT;
DROP TABLE IF EXISTS USER_MANGA;
DROP TABLE IF EXISTS MANGA_GENRE;
DROP TABLE IF EXISTS AUTHOR_GENRE;
DROP TABLE IF EXISTS DRAFTSMAN_MANGA;
DROP TABLE IF EXISTS AUTHOR_MANGA;
DROP TABLE IF EXISTS T_USER;
DROP TABLE IF EXISTS GENRE;
DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS MANGA;

CREATE TABLE MANGA
(
	ID_MANGA 						INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TITLE 							VARCHAR(20) NOT NULL,
	DATE_OF_RELEASE 			DATE,
	STATUS 						VARCHAR(10) CHECK (STATUS IN ('open', 'close')),
	FREQUENCY 					VARCHAR(10) CHECK (FREQUENCY IN ('day', 'week', 'month', 'year')),
	PICTURE 						VARCHAR(20)
);

CREATE TABLE AUTHOR
(
	ID_AUTHOR 					INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME 							VARCHAR(20),
	SURNAME 						VARCHAR(20),
	DATE_OF_BIRTH 				DATE,
	DATE_OF_FIRSTP_UBLISH 	DATE,
	ALIAS 							VARCHAR(20)
);

CREATE TABLE GENRE
(
	ID_GENRE  						INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME      						VARCHAR(20) NOT NULL
);

CREATE TABLE T_USER
(
	ID_USER 						INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME 							VARCHAR(25),
	SURNAME 						VARCHAR(25),
	PASSWORD						VARCHAR(25),
	DATE_OF_BIRTH 				DATE,
	NICKNAME 						VARCHAR(54) UNIQUE,
	NOTIFICATION_D 			CHAR(1) DEFAULT 'Y' CHECK (NOTIFICATION_D IN ('Y', 'N')),
	SHIPPING_ENABED 			CHAR(1) DEFAULT 'N' CHECK (SHIPPING_ENABED IN ('Y', 'N'))
);

CREATE TABLE AUTHOR_MANGA
(
	AUTHOR_ID 					INT UNSIGNED NOT NULL,
	MANGA_ID   					INT UNSIGNED NOT NULL,
	FOREIGN KEY (AUTHOR_ID) 	REFERENCES AUTHOR (ID_AUTHOR) 	ON DELETE CASCADE ,
	FOREIGN KEY (MANGA_ID)  	REFERENCES MANGA (ID_MANGA) 	ON DELETE CASCADE ,
	PRIMARY KEY (AUTHOR_ID, MANGA_ID)
);


CREATE TABLE DRAFTSMAN_MANGA
(
	DRAFTSMAN_ID 				INT UNSIGNED NOT NULL,
	MANGA_ID 						INT UNSIGNED NOT NULL,
	FOREIGN KEY (DRAFTSMAN_ID) 	REFERENCES AUTHOR (ID_AUTHOR) 	ON DELETE CASCADE ,
	FOREIGN KEY (MANGA_ID) 			REFERENCES MANGA (ID_MANGA) 		ON DELETE CASCADE ,
	PRIMARY KEY (DRAFTSMAN_ID, MANGA_ID)
);


CREATE TABLE AUTHOR_GENRE
(
	AUTHOR_ID 					INT UNSIGNED NOT NULL,
	GENRE_ID 						INT UNSIGNED NOT NULL,
	FOREIGN KEY (AUTHOR_ID) 	REFERENCES AUTHOR 	(ID_AUTHOR) 	ON DELETE CASCADE ,
	FOREIGN KEY (GENRE_ID) 	REFERENCES GENRE 	(ID_GENRE) 	ON DELETE CASCADE ,
	PRIMARY KEY (AUTHOR_ID, GENRE_ID)
);

CREATE TABLE USER_GENRE
(
	USER_ID 					INT UNSIGNED NOT NULL,
	GENRE_ID 					INT UNSIGNED NOT NULL,
	FOREIGN KEY (USER_ID) 		REFERENCES T_USER 	(ID_USER) 	ON DELETE CASCADE ,
	FOREIGN KEY (GENRE_ID) 	REFERENCES GENRE 	(ID_GENRE) ON DELETE CASCADE ,
	PRIMARY KEY (USER_ID, GENRE_ID)
);

CREATE TABLE MANGA_GENRE
(
	MANGA_ID 					INT UNSIGNED NOT NULL,
	GENRE_ID 					INT UNSIGNED NOT NULL,
	FOREIGN KEY (MANGA_ID) 	REFERENCES MANGA 	(ID_MANGA) 	ON DELETE CASCADE ,
	FOREIGN KEY (GENRE_ID) 	REFERENCES GENRE 	(ID_GENRE) 	ON DELETE CASCADE ,
	PRIMARY KEY (MANGA_ID, GENRE_ID)
);

CREATE TABLE USER_MANGA
(
	USER_ID 					INT UNSIGNED NOT NULL,
	MANGA_ID 					INT UNSIGNED NOT NULL,
	FOREIGN KEY (USER_ID) 		REFERENCES T_USER 	(ID_USER) 		ON DELETE CASCADE ,
	FOREIGN KEY (MANGA_ID) 	REFERENCES MANGA 	(ID_MANGA) 	ON DELETE CASCADE ,
	PRIMARY KEY (USER_ID, MANGA_ID)
);

CREATE TABLE CHARACT
(
	ID_CHARACT 				INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME 						VARCHAR(25),
	LOOK 						VARCHAR(20),
	AGE 							INT UNSIGNED,
	FIRST_APPEARANCE 		INT UNSIGNED NOT NULL,
	LAST_APPEARANCE 		INT UNSIGNED NOT NULL,
	PICTURE 					VARCHAR(20) NOT NULL
);

CREATE TABLE USER_CHARACT
(
	USER_ID 					INT UNSIGNED NOT NULL,
	CHARACT_ID 				INT UNSIGNED NOT NULL,
	FOREIGN KEY (USER_ID) 			REFERENCES T_USER 		(ID_USER) 		ON DELETE CASCADE ,
	FOREIGN KEY (CHARACT_ID) 	REFERENCES CHARACT 	(ID_CHARACT) ON DELETE CASCADE ,
	PRIMARY KEY (USER_ID, CHARACT_ID)
);


CREATE TABLE PAGE
(
	ID_PAGE     	INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PAGE_NUMBER INT UNSIGNED NOT NULL,
	CHAPTER_ID 	INT UNSIGNED NOT NULL,
	FOREIGN KEY (CHAPTER_ID)  REFERENCES CHARACT  (ID_CHARACT) ON DELETE CASCADE 
);


CREATE TABLE PAGE_CHARACT
(
	PAGE_ID 					INT UNSIGNED NOT NULL,
	CHARACT_ID 				INT UNSIGNED NOT NULL,
	FOREIGN KEY (PAGE_ID) 			REFERENCES PAGE 			(ID_PAGE) 		ON DELETE CASCADE ,
	FOREIGN KEY (CHARACT_ID) 	REFERENCES CHARACT 	(ID_CHARACT) ON DELETE CASCADE ,
	PRIMARY KEY (PAGE_ID, CHARACT_ID)
);


CREATE TABLE MANGA_CHARACT
(
	MANGA_ID 					INT UNSIGNED NOT NULL,
	CHARACT_ID 				INT UNSIGNED NOT NULL,
	FOREIGN KEY (MANGA_ID) 			REFERENCES MANGA 	(ID_MANGA) 		ON DELETE CASCADE ,
	FOREIGN KEY (CHARACT_ID) 	REFERENCES CHARACT 	(ID_CHARACT) ON DELETE CASCADE ,
	PRIMARY KEY (MANGA_ID, CHARACT_ID)
);
CREATE TABLE CHAPTER
(
	ID_CHAPTER 		INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TITLE 				VARCHAR(25) NOT NULL,
	SERIAL_NUMBER 	VARCHAR(12) NOT NULL,
	COVER 				VARCHAR(50),
	MANGA_ID 			INT UNSIGNED NOT NULL,
	FOREIGN KEY (MANGA_ID) REFERENCES MANGA (ID_MANGA) ON DELETE CASCADE ,
	PICTURE 					VARCHAR(20) NOT NULL
);

CREATE TABLE MAGAZINE
(
	ID_MAGAZINE 		INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TITLE 				VARCHAR(25) NOT NULL,
	PICTURE 			VARCHAR(25)
);

CREATE TABLE VOLUME
(
	ID_VOLUME  		INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME 				VARCHAR(25) NOT NULL,
	PICTURE 			VARCHAR(25)
);

CREATE TABLE ADDITIONAL_DATA
(
	ID_ADDITIONAL 	INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TEXT          		BLOB(1500),
	VOLUME_ID     	INT UNSIGNED NOT NULL,
	FOREIGN KEY (VOLUME_ID) REFERENCES VOLUME (ID_VOLUME) ON DELETE CASCADE 
);

CREATE TABLE MAGAZINE_CHAPTER
(
	MAGAZINE_ID 		INT UNSIGNED NOT NULL,
	CHAPTER_ID  		INT UNSIGNED NOT NULL,
	FOREIGN KEY (MAGAZINE_ID) 	REFERENCES MAGAZINE 	(ID_MAGAZINE) 		ON DELETE CASCADE ,
	FOREIGN KEY (CHAPTER_ID) 	REFERENCES CHAPTER 	(ID_CHAPTER) 		ON DELETE CASCADE ,
	PRIMARY KEY (MAGAZINE_ID, CHAPTER_ID)
);


CREATE TABLE VOLUME_CHAPTER
(
	VOLUME_ID  		INT UNSIGNED NOT NULL,
	CHAPTER_ID   		INT UNSIGNED NOT NULL,
	FOREIGN KEY (VOLUME_ID) 	REFERENCES VOLUME 	 (ID_VOLUME) 		ON DELETE CASCADE ,
	FOREIGN KEY (CHAPTER_ID) REFERENCES CHAPTER (ID_CHAPTER) 		ON DELETE CASCADE ,
	PRIMARY KEY (VOLUME_ID, CHAPTER_ID)
);


CREATE TABLE USER_VOLUME
(
	VOLUME_ID   		INT UNSIGNED NOT NULL,
	USER_ID 	   		INT UNSIGNED NOT NULL,
	FOREIGN KEY (VOLUME_ID) 	REFERENCES VOLUME 	 (ID_VOLUME) 	ON DELETE CASCADE ,
	FOREIGN KEY (USER_ID) 		REFERENCES T_USER (ID_USER)	 		ON DELETE CASCADE ,
	PRIMARY KEY (VOLUME_ID, USER_ID)
);



CREATE TABLE USER_MAGAZINE
(
	MAGAZINE_ID 		INT UNSIGNED NOT NULL,
	USER_ID 	   		INT UNSIGNED NOT NULL,
	FOREIGN KEY (MAGAZINE_ID) 	REFERENCES MAGAZINE 	(ID_MAGAZINE) 	ON DELETE CASCADE ,
	FOREIGN KEY (USER_ID) 			REFERENCES T_USER 		(ID_USER)	 		ON DELETE CASCADE ,
	PRIMARY KEY (MAGAZINE_ID, USER_ID)
);

INSERT INTO AUTHOR VALUES 
(NULL, 'John', 'Darth', STR_TO_DATE('21.08.1973', '%d.%m.%Y'), STR_TO_DATE('10.05.1996', '%d.%m.%Y'), 'JD'),
(NULL, 'Ren', 'Tart', STR_TO_DATE('04.12.1985', '%d.%m.%Y'), STR_TO_DATE('14.12.1999', '%d.%m.%Y'), 'RT'),
(NULL, 'Ned', 'Cole', STR_TO_DATE('30.01.1996', '%d.%m.%Y'), STR_TO_DATE('14.12.1999', '%d.%m.%Y'), 'NC'),
(NULL, 'Fael', 'Thedo', STR_TO_DATE('19.04.1979', '%d.%m.%Y'), STR_TO_DATE('14.12.1999', '%d.%m.%Y'), 'FT'),
(NULL, 'Mumbo', 'Jumbo', STR_TO_DATE('28.01.1993', '%d.%m.%Y'), STR_TO_DATE('14.12.1999', '%d.%m.%Y'), 'MJ'),
(NULL, 'Jilly', 'Beat', STR_TO_DATE('01.04.1988', '%d.%m.%Y'), STR_TO_DATE('14.12.1999', '%d.%m.%Y'), 'JB'),
(NULL, 'Loony', 'Douth', STR_TO_DATE('26.03.1986', '%d.%m.%Y'), STR_TO_DATE('14.12.1999', '%d.%m.%Y'), 'LD'),
(NULL, 'Servy', 'Wailer', STR_TO_DATE('16.09.1997', '%d.%m.%Y'), STR_TO_DATE('14.12.1999', '%d.%m.%Y'), 'SW');

INSERT INTO GENRE VALUES 
(NULL, 'Dee'), (NULL, 'Roo'), (NULL, 'Sii'), (NULL, 'Foo'), 
(NULL, 'Nuu'), (NULL, 'Laa'), (NULL, 'Xoo'), (NULL, 'Quu');


INSERT INTO CHARACT VALUES 
(NULL, 'Naruto', 'yellow', '18', '20', '80', 'character_naruto'),
(NULL, 'Sasuke', 'black', '19', '15', '65', 'character_sasuke'),
(NULL, 'Itachi', 'dark', '18', '13', '17', 'character_itachi'),
(NULL, 'Ichigo', 'orange', '19', '10', '53', 'character_ichigo'),
(NULL, 'Goku', 'blue', '18', '2', '28', 'character_goku'),
(NULL, 'Shiro', 'white', '19', '14', '45', 'character_shiro'),
(NULL, 'Zero', 'shadow', '18', '3', '90', 'character_zero'),
(NULL, 'Richard', 'brown', '19', '51', '52', 'character_richard');

INSERT INTO MANGA VALUES 
(NULL, 'Naruto', STR_TO_DATE('11.11.1999', '%d.%m.%Y'), 'open', 'week', 'manga_naruto'),
(NULL, 'Bleach', STR_TO_DATE('11.11.1999', '%d.%m.%Y'), 'close', 'year', 'manga_bleach'),
(NULL, 'NoGameNoLife', STR_TO_DATE('11.11.1999', '%d.%m.%Y'), 'close', 'month', 'manga_nogamenolife'),
(NULL, 'Free', STR_TO_DATE('11.11.1999', '%d.%m.%Y'), 'close', 'week', 'manga_free'),
(NULL, 'DragonBall', STR_TO_DATE('11.11.1999', '%d.%m.%Y'), 'close', 'month', 'manga_dragonball'),
(NULL, 'SAO', STR_TO_DATE('11.11.1999', '%d.%m.%Y'), 'open', 'day', 'manga_sao'),
(NULL, 'Clannad', STR_TO_DATE('11.11.1999', '%d.%m.%Y'), 'close', 'week', 'manga_clannad'),
(NULL, 'LogHorizon', STR_TO_DATE('11.11.1999', '%d.%m.%Y'), 'open', 'year', 'manga_loghorizon'),
(NULL, 'a', STR_TO_DATE('11.11.1999', '%d.%m.%Y'), 'open', 'year', 'manga_a'),
(NULL, 'b', STR_TO_DATE('11.11.1999', '%d.%m.%Y'), 'open', 'year', 'manga_b'),
(NULL, 'c', STR_TO_DATE('11.11.1999', '%d.%m.%Y'), 'open', 'year', 'manga_c'),
(NULL, 'd', STR_TO_DATE('11.11.1999', '%d.%m.%Y'), 'open', 'year', 'manga_d'),
(NULL, 'e', STR_TO_DATE('11.11.1999', '%d.%m.%Y'), 'open', 'year', 'manga_e'),
(NULL, 'f', STR_TO_DATE('11.11.1999', '%d.%m.%Y'), 'open', 'year', 'manga_f');

INSERT INTO T_USER (ID_USER, NAME, SURNAME, PASSWORD, DATE_OF_BIRTH, NICKNAME, NOTIFICATION_D, SHIPPING_ENABED) VALUES 
(NULL, 'Max', 'Milian', '12345', STR_TO_DATE('20.12.1997', '%d.%m.%Y'), 'MM', 'Y', 'N'),
(NULL, 'Fero', 'Mrkva', '12345', STR_TO_DATE('20.12.1997', '%d.%m.%Y'), 'FM', 'Y', 'Y'),
(NULL, 'Michal', 'Lampa', '12345', STR_TO_DATE('20.12.1997', '%d.%m.%Y'), 'ML', 'N', 'N'),
(NULL, 'Martin', 'Hviezda', '12345', STR_TO_DATE('20.12.1997', '%d.%m.%Y'), 'MH', 'N', 'N'),
(NULL, 'Lucia', 'Biela', '12345', STR_TO_DATE('20.12.1997', '%d.%m.%Y'), 'LB', 'Y', 'Y'),
(NULL, 'Hana', 'Zaluze', '12345', STR_TO_DATE('20.12.1997', '%d.%m.%Y'), 'HZ', 'N', 'Y'),
(NULL, 'Petra', 'Tenda', '12345', STR_TO_DATE('20.12.1997', '%d.%m.%Y'), 'PT', 'N', 'Y'),
(NULL, 'Andrea', 'Fixa', '12345', STR_TO_DATE('20.12.1997', '%d.%m.%Y'), 'AF', 'Y', 'N');

INSERT INTO VOLUME (ID_VOLUME, NAME, PICTURE) VALUES (NULL, 'SUPER Avecome volume1', 'SUPER Avecome volume1');
INSERT INTO VOLUME (ID_VOLUME, NAME, PICTURE) VALUES (NULL, 'SUPER Avecome volume2', 'SUPER Avecome volume2');
INSERT INTO VOLUME (ID_VOLUME, NAME, PICTURE) VALUES (NULL, 'SUPER Avecome volume3', 'SUPER Avecome volume3');
INSERT INTO VOLUME (ID_VOLUME, NAME, PICTURE) VALUES (NULL, 'SUPER Avecome volume4', 'SUPER Avecome volume4');
INSERT INTO VOLUME (ID_VOLUME, NAME, PICTURE) VALUES (NULL, 'SUPER Avecome volume5', 'SUPER Avecome volume5');
INSERT INTO VOLUME (ID_VOLUME, NAME, PICTURE) VALUES (NULL, 'SUPER Avecome volume6', 'SUPER Avecome volume6');
INSERT INTO VOLUME (ID_VOLUME, NAME, PICTURE) VALUES (NULL, 'SUPER Avecome volume7', 'SUPER Avecome volume7');
INSERT INTO VOLUME (ID_VOLUME, NAME, PICTURE) VALUES (NULL, 'SUPER Avecome volume8', 'SUPER Avecome volume8');

INSERT INTO MAGAZINE (ID_MAGAZINE, TITLE, PICTURE) VALUES (NULL, 'New', '1');
INSERT INTO MAGAZINE (ID_MAGAZINE, TITLE, PICTURE) VALUES (NULL, 'York', '2');
INSERT INTO MAGAZINE (ID_MAGAZINE, TITLE, PICTURE) VALUES (NULL, 'Times', '3');
INSERT INTO MAGAZINE (ID_MAGAZINE, TITLE, PICTURE) VALUES (NULL, 'Square', '4');
INSERT INTO MAGAZINE (ID_MAGAZINE, TITLE, PICTURE) VALUES (NULL, 'Fit', '5');
INSERT INTO MAGAZINE (ID_MAGAZINE, TITLE, PICTURE) VALUES (NULL, 'Stud', '6');
INSERT INTO MAGAZINE (ID_MAGAZINE, TITLE, PICTURE) VALUES (NULL, 'Vut', '7');
INSERT INTO MAGAZINE (ID_MAGAZINE, TITLE, PICTURE) VALUES (NULL, 'Br', '8');


INSERT INTO PAGE (ID_PAGE, PAGE_NUMBER, CHAPTER_ID) VALUES (NULL, '10', '1');
INSERT INTO PAGE (ID_PAGE, PAGE_NUMBER, CHAPTER_ID) VALUES (NULL, '20', '1');
INSERT INTO PAGE (ID_PAGE, PAGE_NUMBER, CHAPTER_ID) VALUES (NULL, '35', '2');



INSERT INTO CHAPTER (ID_CHAPTER, TITLE, SERIAL_NUMBER, COVER, MANGA_ID)
VALUES (NULL, 'SUPER awesome chapter1', 'a1', 'SOME_URL1', '1');
INSERT INTO CHAPTER (ID_CHAPTER, TITLE, SERIAL_NUMBER, COVER, MANGA_ID)
VALUES (NULL, 'SUPER awesome chapter2', 'b1', 'SOME_URL2', '2');
INSERT INTO CHAPTER (ID_CHAPTER, TITLE, SERIAL_NUMBER, COVER, MANGA_ID)
VALUES (NULL, 'SUPER awesome chapter3', 'c1', 'SOME_URL3', '3');
INSERT INTO CHAPTER (ID_CHAPTER, TITLE, SERIAL_NUMBER, COVER, MANGA_ID)
VALUES (NULL, 'SUPER awesome chapter4', 'd1', 'SOME_URL4', '4');
INSERT INTO CHAPTER (ID_CHAPTER, TITLE, SERIAL_NUMBER, COVER, MANGA_ID)
VALUES (NULL, 'SUPER awesome chapter5', 'e1', 'SOME_URL5', '5');
INSERT INTO CHAPTER (ID_CHAPTER, TITLE, SERIAL_NUMBER, COVER, MANGA_ID)
VALUES (NULL, 'SUPER awesome chapter6', 'f1', 'SOME_URL6', '6');
INSERT INTO CHAPTER (ID_CHAPTER, TITLE, SERIAL_NUMBER, COVER, MANGA_ID)
VALUES (NULL, 'SUPER awesome chapter7', 'g1', 'SOME_URL7', '7');
INSERT INTO CHAPTER (ID_CHAPTER, TITLE, SERIAL_NUMBER, COVER, MANGA_ID)
VALUES (NULL, 'SUPER awesome chapter8', 'h1', 'SOME_URL8', '8');


INSERT INTO MAGAZINE_CHAPTER (MAGAZINE_ID, CHAPTER_ID) VALUES ('1', '1');
INSERT INTO MAGAZINE_CHAPTER (MAGAZINE_ID, CHAPTER_ID) VALUES ('2', '5');
INSERT INTO MAGAZINE_CHAPTER (MAGAZINE_ID, CHAPTER_ID) VALUES ('4', '3');
INSERT INTO MAGAZINE_CHAPTER (MAGAZINE_ID, CHAPTER_ID) VALUES ('3', '7');
INSERT INTO MAGAZINE_CHAPTER (MAGAZINE_ID, CHAPTER_ID) VALUES ('3', '8');

INSERT INTO MANGA_CHARACT (MANGA_ID, CHARACT_ID) VALUES ('1', '1');
INSERT INTO MANGA_CHARACT (MANGA_ID, CHARACT_ID) VALUES ('1', '2');
INSERT INTO MANGA_CHARACT (MANGA_ID, CHARACT_ID) VALUES ('1', '3');
INSERT INTO MANGA_CHARACT (MANGA_ID, CHARACT_ID) VALUES ('2', '4');
INSERT INTO MANGA_CHARACT (MANGA_ID, CHARACT_ID) VALUES ('3', '5');
INSERT INTO MANGA_CHARACT (MANGA_ID, CHARACT_ID) VALUES ('5', '6');
INSERT INTO MANGA_CHARACT (MANGA_ID, CHARACT_ID) VALUES ('7', '7');
INSERT INTO MANGA_CHARACT (MANGA_ID, CHARACT_ID) VALUES ('6', '8');

INSERT INTO USER_CHARACT (USER_ID, CHARACT_ID) VALUES ('1', '1');
INSERT INTO USER_CHARACT (USER_ID, CHARACT_ID) VALUES ('2', '2');
INSERT INTO USER_CHARACT (USER_ID, CHARACT_ID) VALUES ('3', '1');
INSERT INTO USER_CHARACT (USER_ID, CHARACT_ID) VALUES ('4', '3');
INSERT INTO USER_CHARACT (USER_ID, CHARACT_ID) VALUES ('5', '7');
INSERT INTO USER_CHARACT (USER_ID, CHARACT_ID) VALUES ('6', '5');
INSERT INTO USER_CHARACT (USER_ID, CHARACT_ID) VALUES ('8', '6');
INSERT INTO USER_CHARACT (USER_ID, CHARACT_ID) VALUES ('2', '4');
INSERT INTO USER_CHARACT (USER_ID, CHARACT_ID) VALUES ('5', '3');

INSERT INTO USER_MANGA (USER_ID, MANGA_ID) VALUES ('1', '1');
INSERT INTO USER_MANGA (USER_ID, MANGA_ID) VALUES ('2', '1');
INSERT INTO USER_MANGA (USER_ID, MANGA_ID) VALUES ('3', '3');
INSERT INTO USER_MANGA (USER_ID, MANGA_ID) VALUES ('4', '8');
INSERT INTO USER_MANGA (USER_ID, MANGA_ID) VALUES ('8', '6');
INSERT INTO USER_MANGA (USER_ID, MANGA_ID) VALUES ('6', '8');
INSERT INTO USER_MANGA (USER_ID, MANGA_ID) VALUES ('1', '10');
INSERT INTO USER_MANGA (USER_ID, MANGA_ID) VALUES ('2', '12');
INSERT INTO USER_MANGA (USER_ID, MANGA_ID) VALUES ('3', '12');
INSERT INTO USER_MANGA (USER_ID, MANGA_ID) VALUES ('4', '12');
INSERT INTO USER_MANGA (USER_ID, MANGA_ID) VALUES ('5', '10');
INSERT INTO USER_MANGA (USER_ID, MANGA_ID) VALUES ('6', '10');
INSERT INTO USER_MANGA (USER_ID, MANGA_ID) VALUES ('7', '11');

INSERT INTO USER_VOLUME (VOLUME_ID, USER_ID) VALUES ('1', '7');
INSERT INTO USER_VOLUME (VOLUME_ID, USER_ID) VALUES ('3', '5');
INSERT INTO USER_VOLUME (VOLUME_ID, USER_ID) VALUES ('4', '4');
INSERT INTO USER_VOLUME (VOLUME_ID, USER_ID) VALUES ('4', '3');
INSERT INTO USER_VOLUME (VOLUME_ID, USER_ID) VALUES ('5', '5');
INSERT INTO USER_VOLUME (VOLUME_ID, USER_ID) VALUES ('2', '1');

INSERT INTO VOLUME_CHAPTER (VOLUME_ID, CHAPTER_ID) VALUES ('1', '2');
INSERT INTO VOLUME_CHAPTER (VOLUME_ID, CHAPTER_ID) VALUES ('2', '1');
INSERT INTO VOLUME_CHAPTER (VOLUME_ID, CHAPTER_ID) VALUES ('3', '4');
INSERT INTO VOLUME_CHAPTER (VOLUME_ID, CHAPTER_ID) VALUES ('3', '2');
INSERT INTO VOLUME_CHAPTER (VOLUME_ID, CHAPTER_ID) VALUES ('5', '3');
INSERT INTO VOLUME_CHAPTER (VOLUME_ID, CHAPTER_ID) VALUES ('6', '3');


INSERT INTO MANGA_GENRE (MANGA_ID, GENRE_ID) VALUES ('1', '1');
INSERT INTO MANGA_GENRE (MANGA_ID, GENRE_ID) VALUES ('1', '2');
INSERT INTO MANGA_GENRE (MANGA_ID, GENRE_ID) VALUES ('2', '2');


INSERT INTO PAGE_CHARACT (PAGE_ID, CHARACT_ID) VALUES ('1', '2');
INSERT INTO PAGE_CHARACT (PAGE_ID, CHARACT_ID) VALUES ('2', '1');
INSERT INTO PAGE_CHARACT (PAGE_ID, CHARACT_ID) VALUES ('1', '3');


INSERT INTO USER_GENRE (USER_ID, GENRE_ID) VALUES ('1', '2');
INSERT INTO USER_GENRE (USER_ID, GENRE_ID) VALUES ('1', '1');
INSERT INTO USER_GENRE (USER_ID, GENRE_ID) VALUES ('3', '2');

INSERT INTO USER_MAGAZINE (MAGAZINE_ID, USER_ID) VALUES ('1', '1');
INSERT INTO USER_MAGAZINE (MAGAZINE_ID, USER_ID) VALUES ('2', '3');
INSERT INTO USER_MAGAZINE (MAGAZINE_ID, USER_ID) VALUES ('3', '1');

INSERT INTO ADDITIONAL_DATA (ID_ADDITIONAL, TEXT, VOLUME_ID) VALUES ('1', 'sjkteu', '1');
INSERT INTO ADDITIONAL_DATA (ID_ADDITIONAL, TEXT, VOLUME_ID) VALUES ('2', 'djklhe', '2');
INSERT INTO ADDITIONAL_DATA (ID_ADDITIONAL, TEXT, VOLUME_ID) VALUES ('3', 'aougmen', '3');

INSERT INTO DRAFTSMAN_MANGA VALUES ('1', '1');
INSERT INTO DRAFTSMAN_MANGA (DRAFTSMAN_ID, MANGA_ID) VALUES ('3', '2');
INSERT INTO DRAFTSMAN_MANGA (DRAFTSMAN_ID, MANGA_ID) VALUES ('2', '3');
INSERT INTO DRAFTSMAN_MANGA (DRAFTSMAN_ID, MANGA_ID) VALUES ('2', '4');
INSERT INTO DRAFTSMAN_MANGA (DRAFTSMAN_ID, MANGA_ID) VALUES ('3', '5');
INSERT INTO DRAFTSMAN_MANGA (DRAFTSMAN_ID, MANGA_ID) VALUES ('4', '6');
INSERT INTO DRAFTSMAN_MANGA (DRAFTSMAN_ID, MANGA_ID) VALUES ('5', '7');
INSERT INTO DRAFTSMAN_MANGA (DRAFTSMAN_ID, MANGA_ID) VALUES ('1', '8');


INSERT INTO AUTHOR_GENRE (AUTHOR_ID, GENRE_ID) VALUES ('1', '1');
INSERT INTO AUTHOR_GENRE (AUTHOR_ID, GENRE_ID) VALUES ('2', '2');
INSERT INTO AUTHOR_GENRE (AUTHOR_ID, GENRE_ID) VALUES ('3', '3');
INSERT INTO AUTHOR_GENRE (AUTHOR_ID, GENRE_ID) VALUES ('4', '4');
INSERT INTO AUTHOR_GENRE (AUTHOR_ID, GENRE_ID) VALUES ('5', '5');
INSERT INTO AUTHOR_GENRE (AUTHOR_ID, GENRE_ID) VALUES ('6', '6');
INSERT INTO AUTHOR_GENRE (AUTHOR_ID, GENRE_ID) VALUES ('7', '7');
INSERT INTO AUTHOR_GENRE (AUTHOR_ID, GENRE_ID) VALUES ('8', '8');
INSERT INTO AUTHOR_GENRE (AUTHOR_ID, GENRE_ID) VALUES ('2', '8');
INSERT INTO AUTHOR_GENRE (AUTHOR_ID, GENRE_ID) VALUES ('6', '4');

INSERT INTO AUTHOR_MANGA (AUTHOR_ID, MANGA_ID) VALUES ('1', '1');
INSERT INTO AUTHOR_MANGA (AUTHOR_ID, MANGA_ID) VALUES ('2', '2');
INSERT INTO AUTHOR_MANGA (AUTHOR_ID, MANGA_ID) VALUES ('3', '3');
INSERT INTO AUTHOR_MANGA (AUTHOR_ID, MANGA_ID) VALUES ('4', '4');
INSERT INTO AUTHOR_MANGA (AUTHOR_ID, MANGA_ID) VALUES ('5', '5');
INSERT INTO AUTHOR_MANGA (AUTHOR_ID, MANGA_ID) VALUES ('6', '6');
INSERT INTO AUTHOR_MANGA (AUTHOR_ID, MANGA_ID) VALUES ('7', '7');
INSERT INTO AUTHOR_MANGA (AUTHOR_ID, MANGA_ID) VALUES ('8', '8');



